export interface FormContextValue {
  isVehInvolved: string;
  isTpDriverOwner: string;
  tpRegNumber: string;
  tpMake: string;
  tpModel: string;
  tpOwnerName: string;
  tpOwnerTelephone: string;
  tpOwnerAddress: string;
  tpDriverName: string;
  tpDriverTelephone: string;
  tpDriverAddress: string;
  tpInsuranceCompany: string;
  tpPolicyNo: string;
  tpRef: React.RefObject<HTMLFormElement>;
  tpFormData: FormData | null;
  formStep: number;
  isWitness: string;
  witnessName: string;
  witnessAddress: string;
  isPolice: string;
  isInjury: string;
  STEPS_NUMBERS: number;
  driverForm: boolean;
  policeName: string;
  policeStattion: string;
  policeRefN: string;
  accidentDate: Date;
  accidentTime: string;
  accidentLocation: string;
  weatherCondition: string;
  roadCondition: string;
  driverSpeed: string;
  tpSpeed: string;
  driverDamageDetails: string;
  tpDamageDetails: string;
  driverStatement: string;
  driverSignature: string;
  driverDamageVeh: string;
  tpDamageVeh: string;
  schemeBeforeAccident: string;
  schemeAfterAccident: string;

  setIsVehInvolved: (value: string) => void;
  setTpIsDriverOwner: (value: string) => void;
  setTpRegNumber: (value: string) => void;
  setTpMake: (value: string) => void;
  setTpModel: (value: string) => void;
  setTpOwnerName: (value: string) => void;
  setTpOwnerTelephone: (value: string) => void;
  setTpOwnerAddress: (value: string) => void;
  setTpDriverName: (value: string) => void;
  setTpDriverTelephone: (value: string) => void;
  setTpDriverAddress: (value: string) => void;
  setTpInsuranceCompany: (value: string) => void;
  setTpPolicyNo: (value: string) => void;
  setTpFormData: (value: FormData) => void;
  setFormStep: (value: number | ((prev: number) => number)) => void;
  setIsWitness: (value: string) => void;
  setWitnessName: (value: string) => void;
  setWitnessAddress: (value: string) => void;
  setIsPolice: (value: string) => void;
  setIsInjury: (value: string) => void;
  setDriverForm: (value: boolean) => void;
  setPoliceName: (value: string) => void;
  setPoliceStattion: (value: string) => void;
  setPoliceRefN: (value: string) => void;
  setAccidentDate: (value: Date) => void;
  setAccidentTime: (value: string) => void;
  setAccidentLocation: (value: string) => void;
  setWeatherCondition: (value: string) => void;
  setRoadCondition: (value: string) => void;
  setDriverSpeed: (value: string) => void;
  setTpSpeed: (value: string) => void;
  setDriverDamageDetails: (value: string) => void;
  setTpDamageDetails: (value: string) => void;
  setDriverStatement: (value: string) => void;
  setDriverDamageVeh: (value: string) => void;
  setTpDamageVeh: (value: string) => void;
  setSchemeBeforeAccident: (value: string) => void;
  setSchemeAfterAccident: (value: string) => void;
  setDriverSignature: (value: string) => void;
}
